export interface UseCase {
  slug: string;
  title: string;
  searchQuery: string;
  category: string;
  description: string;
  samplePrompt: string;
  toneHint: string;
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
}

export const USE_CASE_CATEGORIES = [
  { id: "personal", label: "Personal & Life Events" },
  { id: "professional", label: "Professional & Career" },
  { id: "business", label: "Business" },
  { id: "content", label: "Content & Creative" },
  { id: "formal", label: "Formal & Official" },
];

export const USE_CASES: UseCase[] = [
  // Personal & Life Events
  { slug: "wedding-speech", title: "Wedding Speech", searchQuery: "write my wedding speech", category: "personal", description: "A wedding speech that sounds like you — your humor, your warmth, the way you actually tell stories.", samplePrompt: "Write a wedding speech for my best friend Sarah's wedding. We've been friends since college. Funny but heartfelt.", toneHint: "warm and personal", faqs: [{ q: "How long should a wedding speech be?", a: "Most great wedding speeches are 3-5 minutes, or about 400-600 words. Long enough to say something meaningful, short enough to hold attention." }, { q: "Can AI write a wedding speech that sounds natural?", a: "DoppelWriter doesn't just generate generic text — it learns YOUR voice first from your writing samples, then drafts a speech that sounds like you actually wrote it." }, { q: "What should I include in a wedding speech?", a: "A great wedding speech has: a personal story about the couple, genuine emotion, a touch of humor, and a heartfelt toast. DoppelWriter can help you structure all of it in your natural voice." }], relatedSlugs: ["best-man-speech", "maid-of-honor-speech", "wedding-vows", "wedding-toast"] },
  { slug: "best-man-speech", title: "Best Man Speech", searchQuery: "write my best man speech", category: "personal", description: "Funny, heartfelt, and actually sounds like something you'd say — not a template from the internet.", samplePrompt: "Write a best man speech for my brother Mike's wedding. Include a funny story about our road trip to Vegas.", toneHint: "funny but sincere", faqs: [{ q: "How do I write a funny best man speech?", a: "The best humor in a best man speech comes from real stories, not jokes. Tell a specific, true story that reveals who the groom really is. DoppelWriter captures your storytelling style so the humor sounds natural." }, { q: "How long should a best man speech be?", a: "3-5 minutes is ideal. That's about 400-600 words — long enough for one great story and a sincere toast." }], relatedSlugs: ["wedding-speech", "wedding-toast", "maid-of-honor-speech"] },
  { slug: "maid-of-honor-speech", title: "Maid of Honor Speech", searchQuery: "write my maid of honor speech", category: "personal", description: "Capture the friendship, the tears, and the joy — in words that sound like yours.", samplePrompt: "Write a maid of honor speech for my sister's wedding. We're very close and I want it to be emotional.", toneHint: "emotional and warm", faqs: [{ q: "What makes a great maid of honor speech?", a: "Authenticity. The best maid of honor speeches feel like a real conversation between friends, not a rehearsed performance." }], relatedSlugs: ["wedding-speech", "best-man-speech", "wedding-toast"] },
  { slug: "wedding-vows", title: "Wedding Vows", searchQuery: "write my wedding vows", category: "personal", description: "The most important words you'll ever say, written in your actual voice.", samplePrompt: "Help me write personal wedding vows for my partner. We've been together 7 years. I want them heartfelt but not cheesy.", toneHint: "deeply personal", faqs: [{ q: "How long should wedding vows be?", a: "1-2 minutes each, or about 150-300 words. Short enough to deliver without breaking down, long enough to mean something." }], relatedSlugs: ["wedding-speech", "love-letter", "anniversary-message"] },
  { slug: "wedding-toast", title: "Wedding Toast", searchQuery: "write a wedding toast", category: "personal", description: "Short, sweet, and perfectly you.", samplePrompt: "Write a brief wedding toast for my colleague's wedding. Keep it warm but not too personal.", toneHint: "warm and brief", faqs: [], relatedSlugs: ["wedding-speech", "best-man-speech"] },
  { slug: "eulogy", title: "Eulogy", searchQuery: "write a eulogy", category: "personal", description: "Honor someone you love with words that sound like they came from your heart — because they did.", samplePrompt: "Write a eulogy for my father. He was a quiet man who loved fishing and making people laugh.", toneHint: "reverent and personal", faqs: [{ q: "How do I write a eulogy for my father?", a: "Focus on specific memories, not generalizations. One real story about who he was says more than a list of accomplishments. DoppelWriter helps you find the words when grief makes it hard to write." }, { q: "How long should a eulogy be?", a: "5-10 minutes, or about 700-1,200 words. Give yourself enough room to share meaningful stories." }], relatedSlugs: ["condolence-message", "obituary", "thank-you-note"] },
  { slug: "condolence-message", title: "Condolence Message", searchQuery: "write a condolence message", category: "personal", description: "Finding the right words is hard. We help you say what you feel.", samplePrompt: "Write a condolence message for my friend whose mother just passed. I want it to be genuine, not generic.", toneHint: "gentle and sincere", faqs: [{ q: "What do you say in a condolence message?", a: "Acknowledge the loss specifically, share a memory if you have one, and offer specific support. DoppelWriter helps you say this in your own voice." }], relatedSlugs: ["eulogy", "thank-you-note", "sympathy-card"] },
  { slug: "thank-you-note", title: "Thank You Note", searchQuery: "write a thank you note", category: "personal", description: "Gratitude that sounds genuine, not generic.", samplePrompt: "Write a thank you note to my mentor who helped me get my first job.", toneHint: "grateful and warm", faqs: [], relatedSlugs: ["condolence-message", "recommendation-letter", "follow-up-email"] },
  { slug: "love-letter", title: "Love Letter", searchQuery: "write a love letter", category: "personal", description: "Your feelings, your words — we just help you get them on paper.", samplePrompt: "Write a love letter to my partner for our anniversary. I'm not great with words but I feel a lot.", toneHint: "romantic and honest", faqs: [], relatedSlugs: ["wedding-vows", "anniversary-message", "dating-profile"] },
  { slug: "anniversary-message", title: "Anniversary Message", searchQuery: "write an anniversary message", category: "personal", description: "Mark the milestone with words that actually sound like you.", samplePrompt: "Write a heartfelt anniversary message for my wife. 10 years together.", toneHint: "reflective and loving", faqs: [], relatedSlugs: ["love-letter", "wedding-vows", "birthday-message"] },
  { slug: "birthday-message", title: "Birthday Message", searchQuery: "write a birthday message", category: "personal", description: "Go beyond 'Happy Birthday' with something that sounds like you.", samplePrompt: "Write a meaningful birthday message for my mom turning 60.", toneHint: "warm and celebratory", faqs: [], relatedSlugs: ["thank-you-note", "anniversary-message"] },
  { slug: "dating-profile", title: "Dating Profile", searchQuery: "write my dating profile", category: "personal", description: "A dating profile that actually sounds like you — not every other profile on the app.", samplePrompt: "Write a Hinge profile for me. I'm a 28-year-old software engineer who loves hiking and bad puns.", toneHint: "authentic and appealing", faqs: [{ q: "Can AI write a good dating profile?", a: "Only if it sounds like you. Generic AI dating profiles are obvious and off-putting. DoppelWriter learns your actual voice first, so your profile has your real personality." }], relatedSlugs: ["linkedin-summary", "professional-bio"] },
  { slug: "graduation-speech", title: "Graduation Speech", searchQuery: "write a graduation speech", category: "personal", description: "Inspire without sounding like every other graduation speech.", samplePrompt: "Write a graduation speech for my high school's senior class.", toneHint: "inspirational but real", faqs: [], relatedSlugs: ["retirement-speech", "wedding-speech"] },
  { slug: "retirement-speech", title: "Retirement Speech", searchQuery: "write a retirement speech", category: "personal", description: "Look back on a career with words that carry your voice.", samplePrompt: "Write a retirement speech after 30 years at the company. Grateful but ready for what's next.", toneHint: "reflective and optimistic", faqs: [], relatedSlugs: ["graduation-speech", "thank-you-note"] },
  { slug: "apology-letter", title: "Apology Letter", searchQuery: "write an apology letter", category: "personal", description: "Say you're sorry in a way that sounds genuine — because it is.", samplePrompt: "Write an apology letter to my friend for missing their wedding.", toneHint: "humble and sincere", faqs: [], relatedSlugs: ["condolence-message", "formal-letter"] },
  { slug: "sympathy-card", title: "Sympathy Card", searchQuery: "what to write in a sympathy card", category: "personal", description: "The right words when you don't know what to say.", samplePrompt: "Write a sympathy card message for a coworker who lost their spouse.", toneHint: "gentle and genuine", faqs: [], relatedSlugs: ["condolence-message", "eulogy", "thank-you-note"] },

  // Professional & Career
  { slug: "cover-letter", title: "Cover Letter", searchQuery: "write my cover letter", category: "professional", description: "A cover letter that sounds like a real person wrote it — because your voice is in it.", samplePrompt: "Write a cover letter for a senior product manager role at Stripe. Emphasize my 5 years of experience.", toneHint: "professional but personable", faqs: [{ q: "Can AI write a good cover letter?", a: "Most AI cover letters sound generic. DoppelWriter is different — it learns your writing voice first, then generates a cover letter that sounds authentically you." }, { q: "How long should a cover letter be?", a: "One page, 250-400 words. Three paragraphs: why this company, what you bring, and a confident close." }], relatedSlugs: ["resume", "linkedin-summary", "personal-statement"] },
  { slug: "resume", title: "Resume", searchQuery: "write my resume", category: "professional", description: "Your career, your voice, properly formatted.", samplePrompt: "Write resume bullet points for my 3 years as a marketing manager at a startup.", toneHint: "professional and concise", faqs: [], relatedSlugs: ["cover-letter", "linkedin-summary", "professional-bio"] },
  { slug: "personal-statement", title: "Personal Statement", searchQuery: "write my personal statement", category: "professional", description: "Your story, told in your voice — not a template.", samplePrompt: "Write a personal statement for my MBA application to Wharton.", toneHint: "reflective and ambitious", faqs: [{ q: "How long should a personal statement be?", a: "Typically 500-1,000 words depending on the program. Quality over quantity — every sentence should earn its place." }], relatedSlugs: ["cover-letter", "recommendation-letter", "essay"] },
  { slug: "recommendation-letter", title: "Recommendation Letter", searchQuery: "write a recommendation letter", category: "professional", description: "Recommend someone in words that sound like yours, not a template.", samplePrompt: "Write a recommendation letter for my direct report applying to graduate school in data science.", toneHint: "supportive and specific", faqs: [], relatedSlugs: ["cover-letter", "reference-letter", "personal-statement"] },
  { slug: "resignation-letter", title: "Resignation Letter", searchQuery: "write my resignation letter", category: "professional", description: "Leave gracefully with a letter that sounds professional and authentically you.", samplePrompt: "Write a resignation letter. I'm leaving for a better opportunity. Keep it positive.", toneHint: "gracious and professional", faqs: [], relatedSlugs: ["formal-letter", "thank-you-note", "follow-up-email"] },
  { slug: "linkedin-post", title: "LinkedIn Post", searchQuery: "write my LinkedIn post", category: "professional", description: "LinkedIn posts that sound like you, not like every other 'thought leader' on the platform.", samplePrompt: "Write a LinkedIn post about a lesson I learned from failing at my first startup.", toneHint: "authentic and insightful", faqs: [{ q: "How do I write LinkedIn posts that get engagement?", a: "Be specific, be personal, and have a point. DoppelWriter captures your natural voice so your posts don't sound like AI-generated leadership cliches." }], relatedSlugs: ["linkedin-summary", "twitter-thread", "blog-post"] },
  { slug: "linkedin-summary", title: "LinkedIn Summary", searchQuery: "write my LinkedIn summary", category: "professional", description: "A LinkedIn About section that sounds like you talking at a dinner party, not a corporate bio.", samplePrompt: "Write a LinkedIn summary for a startup founder in the fintech space.", toneHint: "professional but approachable", faqs: [], relatedSlugs: ["linkedin-post", "professional-bio", "elevator-pitch"] },
  { slug: "professional-bio", title: "Professional Bio", searchQuery: "write my professional bio", category: "professional", description: "Your bio, your voice — not the same template everyone else uses.", samplePrompt: "Write a professional bio for a conference speaker page. I'm a VP of Engineering.", toneHint: "confident and approachable", faqs: [], relatedSlugs: ["linkedin-summary", "about-page", "author-bio"] },
  { slug: "cold-email", title: "Cold Email", searchQuery: "write a cold email", category: "professional", description: "Cold emails that sound human. Because robotic outreach gets deleted.", samplePrompt: "Write a cold email to a potential investor for my Series A.", toneHint: "direct and personable", faqs: [], relatedSlugs: ["follow-up-email", "networking-email", "elevator-pitch"] },
  { slug: "follow-up-email", title: "Follow-Up Email", searchQuery: "write a follow-up email", category: "professional", description: "Follow up without being annoying — in your natural voice.", samplePrompt: "Write a follow-up email after a job interview for a design director role.", toneHint: "warm and professional", faqs: [], relatedSlugs: ["cold-email", "thank-you-note", "networking-email"] },
  { slug: "networking-email", title: "Networking Email", searchQuery: "write a networking email", category: "professional", description: "Reach out to someone you admire without sounding desperate or fake.", samplePrompt: "Write a networking email to a VP at Google I met briefly at a conference.", toneHint: "genuine and respectful", faqs: [], relatedSlugs: ["cold-email", "follow-up-email", "linkedin-post"] },
  { slug: "elevator-pitch", title: "Elevator Pitch", searchQuery: "write my elevator pitch", category: "professional", description: "30 seconds to make an impression — in your words, not a script.", samplePrompt: "Write a 30-second elevator pitch for my AI-powered fitness app.", toneHint: "energetic and clear", faqs: [], relatedSlugs: ["cold-email", "linkedin-summary", "business-proposal"] },

  // Business
  { slug: "business-proposal", title: "Business Proposal", searchQuery: "write a business proposal", category: "business", description: "Persuasive proposals that sound like your team, not a template.", samplePrompt: "Write a business proposal for a partnership between our SaaS company and a Fortune 500 client.", toneHint: "persuasive and professional", faqs: [], relatedSlugs: ["executive-summary", "cold-email", "investor-update"] },
  { slug: "executive-summary", title: "Executive Summary", searchQuery: "write an executive summary", category: "business", description: "Get to the point — clearly, persuasively, in your voice.", samplePrompt: "Write an executive summary for our Q4 2025 strategic plan.", toneHint: "clear and authoritative", faqs: [], relatedSlugs: ["business-proposal", "investor-update", "press-release"] },
  { slug: "press-release", title: "Press Release", searchQuery: "write a press release", category: "business", description: "Announce your news in a way that actually gets read.", samplePrompt: "Write a press release announcing our $10M Series A funding round.", toneHint: "professional and newsworthy", faqs: [], relatedSlugs: ["executive-summary", "company-bio", "product-description"] },
  { slug: "newsletter", title: "Newsletter", searchQuery: "write my newsletter", category: "business", description: "A newsletter your subscribers actually want to read — because it sounds like you.", samplePrompt: "Write a weekly newsletter about trends in the creator economy.", toneHint: "engaging and opinionated", faqs: [], relatedSlugs: ["substack-post", "blog-post", "linkedin-post"] },
  { slug: "product-description", title: "Product Description", searchQuery: "write a product description", category: "business", description: "Describe your product in your brand's actual voice.", samplePrompt: "Write a product description for a premium wireless earbud targeting audiophiles.", toneHint: "compelling and specific", faqs: [], relatedSlugs: ["about-page", "press-release", "instagram-caption"] },
  { slug: "about-page", title: "About Page", searchQuery: "write my about page", category: "business", description: "Tell your story in your voice — not corporate boilerplate.", samplePrompt: "Write an About page for a boutique coffee roaster started by two friends.", toneHint: "authentic and warm", faqs: [], relatedSlugs: ["mission-statement", "company-bio", "professional-bio"] },
  { slug: "mission-statement", title: "Mission Statement", searchQuery: "write a mission statement", category: "business", description: "Your mission, in words that actually mean something.", samplePrompt: "Write a mission statement for an edtech startup focused on adult learners.", toneHint: "purposeful and clear", faqs: [], relatedSlugs: ["about-page", "company-bio", "executive-summary"] },
  { slug: "investor-update", title: "Investor Update", searchQuery: "write an investor update", category: "business", description: "Keep your investors informed in your natural founder voice.", samplePrompt: "Write a monthly investor update. Revenue up 40%, hired 3 engineers, launching new feature.", toneHint: "transparent and confident", faqs: [], relatedSlugs: ["executive-summary", "business-proposal", "newsletter"] },

  // Content & Creative
  { slug: "blog-post", title: "Blog Post", searchQuery: "write my blog post", category: "content", description: "Blog posts that sound like you wrote them — because your voice is in every sentence.", samplePrompt: "Write a blog post about why remote work is better for creative people.", toneHint: "conversational and insightful", faqs: [{ q: "Can AI write blog posts that don't sound like AI?", a: "Only if the AI knows your voice. DoppelWriter analyzes your writing style first, then generates posts that match your rhythm, vocabulary, and personality." }], relatedSlugs: ["substack-post", "linkedin-post", "essay"] },
  { slug: "essay", title: "Essay", searchQuery: "write my essay", category: "content", description: "Your ideas, your voice, properly structured.", samplePrompt: "Write an essay about how social media changed the way we form friendships.", toneHint: "thoughtful and structured", faqs: [], relatedSlugs: ["blog-post", "personal-statement", "substack-post"] },
  { slug: "substack-post", title: "Substack Post", searchQuery: "write my Substack", category: "content", description: "Newsletter-style writing that keeps subscribers coming back.", samplePrompt: "Write a Substack post analyzing why subscription fatigue is real.", toneHint: "opinionated and engaging", faqs: [], relatedSlugs: ["newsletter", "blog-post", "essay"] },
  { slug: "twitter-thread", title: "Twitter/X Thread", searchQuery: "write a Twitter thread", category: "content", description: "Threads that sound like you, not like engagement bait.", samplePrompt: "Write a 10-tweet thread about lessons from bootstrapping a $1M business.", toneHint: "punchy and authentic", faqs: [], relatedSlugs: ["linkedin-post", "instagram-caption", "blog-post"] },
  { slug: "instagram-caption", title: "Instagram Caption", searchQuery: "write my Instagram caption", category: "content", description: "Captions with personality — yours.", samplePrompt: "Write an Instagram caption for a photo from my trip to Japan.", toneHint: "casual and visual", faqs: [], relatedSlugs: ["twitter-thread", "dating-profile", "product-description"] },
  { slug: "youtube-script", title: "YouTube Script", searchQuery: "write a YouTube script", category: "content", description: "Scripts that sound like you talk, not like you're reading.", samplePrompt: "Write a YouTube script for a 10-minute video reviewing the new MacBook Pro.", toneHint: "conversational and engaging", faqs: [], relatedSlugs: ["podcast-intro", "blog-post", "twitter-thread"] },
  { slug: "podcast-intro", title: "Podcast Intro", searchQuery: "write a podcast intro", category: "content", description: "Hook listeners in the first 30 seconds — in your voice.", samplePrompt: "Write a podcast intro for an episode about the future of AI in education.", toneHint: "energetic and inviting", faqs: [], relatedSlugs: ["youtube-script", "newsletter", "speech"] },
  { slug: "author-bio", title: "Author Bio", searchQuery: "write my author bio", category: "content", description: "The bio at the end of your article — short, sharp, you.", samplePrompt: "Write a 2-sentence author bio for a technology journalist.", toneHint: "concise and professional", faqs: [], relatedSlugs: ["professional-bio", "linkedin-summary", "about-page"] },
  { slug: "speech", title: "Speech", searchQuery: "write a speech", category: "content", description: "Any speech, any occasion — in your voice.", samplePrompt: "Write a 5-minute speech for a company all-hands meeting about our new strategic direction.", toneHint: "confident and inspiring", faqs: [], relatedSlugs: ["wedding-speech", "graduation-speech", "retirement-speech"] },
  { slug: "gofundme", title: "GoFundMe Page", searchQuery: "write my GoFundMe", category: "content", description: "Tell your story in a way that moves people to help.", samplePrompt: "Write a GoFundMe page to raise money for my dog's emergency surgery.", toneHint: "honest and emotional", faqs: [], relatedSlugs: ["about-page", "thank-you-note"] },

  // Formal & Official
  { slug: "complaint-letter", title: "Complaint Letter", searchQuery: "write a complaint letter", category: "formal", description: "Get results with a clear, firm complaint that sounds like you.", samplePrompt: "Write a complaint letter to my landlord about repeated maintenance issues.", toneHint: "firm and factual", faqs: [], relatedSlugs: ["formal-letter", "appeal-letter"] },
  { slug: "formal-letter", title: "Formal Letter", searchQuery: "write a formal letter", category: "formal", description: "Proper formatting, professional tone — still sounds like a human.", samplePrompt: "Write a formal letter to my child's school requesting accommodations.", toneHint: "formal and clear", faqs: [], relatedSlugs: ["complaint-letter", "reference-letter", "appeal-letter"] },
  { slug: "reference-letter", title: "Reference Letter", searchQuery: "write a reference letter", category: "formal", description: "Vouch for someone in words that carry your credibility.", samplePrompt: "Write a character reference letter for a friend's custody hearing.", toneHint: "sincere and authoritative", faqs: [], relatedSlugs: ["recommendation-letter", "formal-letter"] },
  { slug: "appeal-letter", title: "Appeal Letter", searchQuery: "write an appeal letter", category: "formal", description: "Make your case clearly and persuasively.", samplePrompt: "Write an appeal letter for a denied insurance claim.", toneHint: "logical and persistent", faqs: [], relatedSlugs: ["complaint-letter", "formal-letter", "hardship-letter"] },
  { slug: "hardship-letter", title: "Hardship Letter", searchQuery: "write a hardship letter", category: "formal", description: "Explain your situation honestly to get the help you need.", samplePrompt: "Write a hardship letter to my mortgage lender requesting forbearance.", toneHint: "honest and urgent", faqs: [], relatedSlugs: ["appeal-letter", "formal-letter", "gofundme"] },
];
