export const WRITER_PHOTOS: Record<string, string> = {
  "Abraham Lincoln": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Abraham_Lincoln_1863_Portrait_%283x4_cropped%29.jpg/200px-Abraham_Lincoln_1863_Portrait_%283x4_cropped%29.jpg",
  "Alain de Botton": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Alain_de_Botton.jpg/330px-Alain_de_Botton.jpg",
  "Alan Watts": "https://upload.wikimedia.org/wikipedia/en/9/97/Alan_Watts.png",
  "Alexandria Ocasio-Cortez": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Alexandria_Ocasio-Cortez_Official_Portrait.jpg/200px-Alexandria_Ocasio-Cortez_Official_Portrait.jpg",
  "Annie Dillard": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Annie-dillard.jpg",
  "Anthony Bourdain": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Anthony_Bourdain_Peabody_2014b.jpg/330px-Anthony_Bourdain_Peabody_2014b.jpg",
  "Atul Gawande": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Atul_Gawande%2C_USAID_Assistant_Administrator.jpg/330px-Atul_Gawande%2C_USAID_Assistant_Administrator.jpg",
  "Ayn Rand": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ayn_Rand_%281943_Talbot_portrait%29.jpg/200px-Ayn_Rand_%281943_Talbot_portrait%29.jpg",
  "Barack Obama": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/200px-President_Barack_Obama.jpg",
  "Ben Thompson": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Ben_Thompson_-_Innholdprodusentens_d%C3%B8d_og_mulige_gjenoppstandelse_-_NMD_2016_%2826890581672%29_%28cropped%29.jpg/200px-Ben_Thompson_-_Innholdprodusentens_d%C3%B8d_og_mulige_gjenoppstandelse_-_NMD_2016_%2826890581672%29_%28cropped%29.jpg",
  "Benjamin Franklin": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg/200px-Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg",
  "Bernie Sanders": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Bernie_Sanders_2023.jpg/200px-Bernie_Sanders_2023.jpg",
  "Beverly Cleary": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Beverly_Cleary_ca._1955.jpg/200px-Beverly_Cleary_ca._1955.jpg",
  "Bo Burnham": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Bo_Burnham_Montaclair_Film_Festival_%28cropped%29.jpg/200px-Bo_Burnham_Montaclair_Film_Festival_%28cropped%29.jpg",
  "Bob Woodward": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bob_Woodward_Oct23_%2853297480588%29.jpg/200px-Bob_Woodward_Oct23_%2853297480588%29.jpg",
  "Brene Brown": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bren%C3%A9_Brown_and_Malcolm_Gladwell_at_SXSW_2025_06_%28cropped%29.jpg/200px-Bren%C3%A9_Brown_and_Malcolm_Gladwell_at_SXSW_2025_06_%28cropped%29.jpg",
  "Byung-Chul Han": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/2015_Byung-Chul_Han_%283x4_cropped%29.jpg/330px-2015_Byung-Chul_Han_%283x4_cropped%29.jpg",
  "C.S. Lewis": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/CS_Lewis_photo_on_dust_jacket.jpg/200px-CS_Lewis_photo_on_dust_jacket.jpg",
  "Carl Sagan": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Carl_Sagan_Planetary_Society.JPG/200px-Carl_Sagan_Planetary_Society.JPG",
  "Charles Dickens": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Dickens_Gurney_head.jpg/330px-Dickens_Gurney_head.jpg",
  "Chimamanda Ngozi Adichie": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Chimamanda_Ngozi_Adichie_%282015%29.png/330px-Chimamanda_Ngozi_Adichie_%282015%29.png",
  "Colleen Hoover": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Colleen_Hoover_Video_Call.png",
  "Conan O'Brien": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Conan_O%27Brien_at_the_2025_Sundance_Film_Festival_03_%28cropped%29.jpg/200px-Conan_O%27Brien_at_the_2025_Sundance_Film_Festival_03_%28cropped%29.jpg",
  "Cormac McCarthy": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Cormac_McCarthy_%28Child_of_God_author_portrait_-_high-res%29.jpg/200px-Cormac_McCarthy_%28Child_of_God_author_portrait_-_high-res%29.jpg",
  "Dave Chappelle": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Dave_Chappelle_at_Preamiere_of_%22Dave_Chappelle_In_Real_Life%22_%282%29.jpg/200px-Dave_Chappelle_at_Preamiere_of_%22Dave_Chappelle_In_Real_Life%22_%282%29.jpg",
  "David Foster Wallace": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/David_Foster_Wallace_in_2006.jpg/200px-David_Foster_Wallace_in_2006.jpg",
  "David Ogilvy": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/David_ogilvy.jpg/200px-David_ogilvy.jpg",
  "David Sedaris": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/David_Sedaris-4724.jpg/200px-David_Sedaris-4724.jpg",
  "Dax Shepard": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Dax_Shepard_2014.jpg/200px-Dax_Shepard_2014.jpg",
  "Dr. Seuss": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Theodor_Seuss_Geisel_%2801037v%29.jpg/200px-Theodor_Seuss_Geisel_%2801037v%29.jpg",
  "Ed Yong": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Ed_Yong_%28cropped%29.JPG/330px-Ed_Yong_%28cropped%29.JPG",
  "Eric Carle": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eric_Carle_kinderboekenschrijver%2C_1988_-_28_%28cropped%29.jpg/200px-Eric_Carle_kinderboekenschrijver%2C_1988_-_28_%28cropped%29.jpg",
  "Ernest Hemingway": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/ErnestHemingway.jpg/200px-ErnestHemingway.jpg",
  "Ezra Klein": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Ezra_Klein_2026-01-28.jpg/200px-Ezra_Klein_2026-01-28.jpg",
  "Fran Lebowitz": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Christopher_Macsurak_Fran_Lebowitz.jpg/330px-Christopher_Macsurak_Fran_Lebowitz.jpg",
  "Frederick Douglass": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Frederick_Douglass_%28circa_1879%29_%28cropped%29.jpg/200px-Frederick_Douglass_%28circa_1879%29_%28cropped%29.jpg",
  "Friedrich Nietzsche": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/200px-Nietzsche187a.jpg",
  "Gay Talese": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Gay_Talese_by_David_Shankbone.jpg/200px-Gay_Talese_by_David_Shankbone.jpg",
  "George Carlin": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/George_Carlin_1975_%28Little_David_Records%29_Publicity.jpg/200px-George_Carlin_1975_%28Little_David_Records%29_Publicity.jpg",
  "George Orwell": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/George_Orwell_press_photo.jpg/200px-George_Orwell_press_photo.jpg",
  "George Packer": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/P1102426georgepacker.jpg/330px-P1102426georgepacker.jpg",
  "Guy Raz": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Guy_Raz_2015-09-29_%28cropped%29.jpg/200px-Guy_Raz_2015-09-29_%28cropped%29.jpg",
  "H.L. Mencken": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/H-L-Mencken-1928.jpg/330px-H-L-Mencken-1928.jpg",
  "Hannah Arendt": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg/200px-Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg",
  "Haruki Murakami": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Conversatorio_Haruki_Murakami_%2812_de_12%29_%2845747009452%29_%28cropped%29.jpg/330px-Conversatorio_Haruki_Murakami_%2812_de_12%29_%2845747009452%29_%28cropped%29.jpg",
  "Howard Marks": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Howard_Marks_2.17.12_%28cropped%29.jpg/330px-Howard_Marks_2.17.12_%28cropped%29.jpg",
  "Hunter S. Thompson": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Hunter_S._Thompson%2C_Las_Vegas_1971.jpg/200px-Hunter_S._Thompson%2C_Las_Vegas_1971.jpg",
  "Isabel Allende": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Isabel_Allende_Frankfurter_Buchmesse_2015_%28cropped%29.JPG/330px-Isabel_Allende_Frankfurter_Buchmesse_2015_%28cropped%29.JPG",
  "J.K. Rowling": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J._K._Rowling_2010.jpg/200px-J._K._Rowling_2010.jpg",
  "James Baldwin": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/James_Baldwin_37_Allan_Warren_%28cropped%29.jpg/330px-James_Baldwin_37_Allan_Warren_%28cropped%29.jpg",
  "James Clear": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/James_Clear_in_2010.jpg/200px-James_Clear_in_2010.jpg",
  "Jane Austen": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/CassandraAusten-JaneAusten%28c.1810%29_hires.jpg/330px-CassandraAusten-JaneAusten%28c.1810%29_hires.jpg",
  "Jeff Bezos": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Jeff_Bezos_visits_LAAFB_SMC_%283908618%29_%28cropped%29.jpeg/200px-Jeff_Bezos_visits_LAAFB_SMC_%283908618%29_%28cropped%29.jpeg",
  "Jenny Slate": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Jenny_Slate_%28cropped%29.jpg/330px-Jenny_Slate_%28cropped%29.jpg",
  "Jerry Seinfeld": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Jerry_Seinfeld_2023.jpg/200px-Jerry_Seinfeld_2023.jpg",
  "Joan Didion": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Didion1970_%28cropped%29.jpg/200px-Didion1970_%28cropped%29.jpg",
  "Joe Rogan": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Joe_Rogan.png/200px-Joe_Rogan.png",
  "John F. Kennedy": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg/200px-John_F._Kennedy%2C_White_House_color_photo_portrait.jpg",
  "John Mulaney": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/John_Mulaney_PaleyFest_crop.jpg/200px-John_Mulaney_PaleyFest_crop.jpg",
  "Jordan Peterson": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Jordan_Peterson_in_2018_%283x4_cropped%29.jpg/200px-Jordan_Peterson_in_2018_%283x4_cropped%29.jpg",
  "Judy Blume": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/JudyBlume2009%28cropped%29.jpg/200px-JudyBlume2009%28cropped%29.jpg",
  "Kara Swisher": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Kara_Swisher_crop.jpg/330px-Kara_Swisher_crop.jpg",
  "Kurt Vonnegut": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Kurt_Vonnegut_by_Bernard_Gotfryd_%281965%29.jpg/200px-Kurt_Vonnegut_by_Bernard_Gotfryd_%281965%29.jpg",
  "Lemony Snicket": "https://upload.wikimedia.org/wikipedia/en/1/1a/Patrick_Warburton_as_Lemony_Snicket.png",
  "Lex Fridman": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Lex_Fridman_teaching_at_MIT_in_2018.png/200px-Lex_Fridman_teaching_at_MIT_in_2018.png",
  "Malcolm Gladwell": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Malcolm_Gladwell%2C_author%2C_at_SXSW_2025_02_%28cropped%29.jpg/200px-Malcolm_Gladwell%2C_author%2C_at_SXSW_2025_02_%28cropped%29.jpg",
  "Marc Andreessen": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Marc_Andreessen-9_%28cropped%29.jpg/200px-Marc_Andreessen-9_%28cropped%29.jpg",
  "Marcus Aurelius": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/MSR-ra-61-b-1-DM.jpg/200px-MSR-ra-61-b-1-DM.jpg",
  "Margaret Thatcher": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Margaret_Thatcher_stock_portrait_%28cropped%29.jpg/200px-Margaret_Thatcher_stock_portrait_%28cropped%29.jpg",
  "Maria Popova": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Maria_Popova_%282%29.jpg/200px-Maria_Popova_%282%29.jpg",
  "Mark Twain": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Twain_by_AF_Bradley.jpg/330px-Mark_Twain_by_AF_Bradley.jpg",
  "Martin Luther King Jr.": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Martin_Luther_King%2C_Jr..jpg/200px-Martin_Luther_King%2C_Jr..jpg",
  "Mary Oliver": "https://upload.wikimedia.org/wikipedia/en/4/4d/Mary_Oliver.jpg",
  "Mary Roach": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/2025_Mary_Roach_at_the_Library_of_Congress_on_25_September_%28cropped%29.jpg/330px-2025_Mary_Roach_at_the_Library_of_Congress_on_25_September_%28cropped%29.jpg",
  "Mary Shelley": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Mary_Wollstonecraft_Shelley_Rothwell.tif/lossy-page1-330px-Mary_Wollstonecraft_Shelley_Rothwell.tif.jpg",
  "Matt Levine": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Matt_levine.jpg/250px-Matt_levine.jpg",
  "Matt Taibbi": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Matt_Taibbi_on_ReasonTV.jpg/200px-Matt_Taibbi_on_ReasonTV.jpg",
  "Maureen Dowd": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Maureen_dowd_%28cropped%29.jpg/200px-Maureen_dowd_%28cropped%29.jpg",
  "Maurice Sendak": "https://upload.wikimedia.org/wikipedia/en/1/11/Maurice-Sendak_portrait2.jpg",
  "Mike Birbiglia": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/MikeBirbiglia_2020_Photo_by_JesseAustin.jpg/330px-MikeBirbiglia_2020_Photo_by_JesseAustin.jpg",
  "Mindy Kaling": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mindy_Kaling_by_Claire_Leahy_%28cropped%29.jpg/200px-Mindy_Kaling_by_Claire_Leahy_%28cropped%29.jpg",
  "Nassim Taleb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Taleb_mug.JPG/200px-Taleb_mug.JPG",
  "Naval Ravikant": "https://upload.wikimedia.org/wikipedia/commons/5/55/Naval_Ravikant_%28cropped%29.jpg",
  "Neil deGrasse Tyson": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Neil_DeGrasse_Tyson_%282023%29.jpg/330px-Neil_DeGrasse_Tyson_%282023%29.jpg",
  "Nelson Mandela": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Nelson_Mandela_1994.jpg/330px-Nelson_Mandela_1994.jpg",
  "Nora Ephron": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Nora_Ephron.jpg/200px-Nora_Ephron.jpg",
  "Oliver Sacks": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Dr._Oliver_Sacks%2C_Physician%2C_Author.jpg/330px-Dr._Oliver_Sacks%2C_Physician%2C_Author.jpg",
  "Oscar Wilde": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Oscar_Wilde_by_Napoleon_Sarony._Three-quarter-length_photograph%2C_seated.jpg/330px-Oscar_Wilde_by_Napoleon_Sarony._Three-quarter-length_photograph%2C_seated.jpg",
  "Patrick Collison": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Patrick_Collison_%28cropped%29.jpg/330px-Patrick_Collison_%28cropped%29.jpg",
  "Paul Graham": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Paulgraham_240x320.jpg/200px-Paulgraham_240x320.jpg",
  "Philip Pullman": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Philip_Pullman_2005-04-16.png/330px-Philip_Pullman_2005-04-16.png",
  "R.L. Stine": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/RLStine.jpg/200px-RLStine.jpg",
  "Rachel Carson": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Rachel-Carson.jpg/330px-Rachel-Carson.jpg",
  "Ralph Waldo Emerson": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ralph_Waldo_Emerson_by_Josiah_Johnson_Hawes_1857.jpg/330px-Ralph_Waldo_Emerson_by_Josiah_Johnson_Hawes_1857.jpg",
  "Ray Dalio": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Web_Summit_2018_-_Forum_-_Day_2%2C_November_7_HM1_7481_%2844858045925%29.jpg/330px-Web_Summit_2018_-_Forum_-_Day_2%2C_November_7_HM1_7481_%2844858045925%29.jpg",
  "Rebecca Solnit": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/2026-03-02_Rebecca_Solnit_at_the_Internet_Archive.jpg/330px-2026-03-02_Rebecca_Solnit_at_the_Internet_Archive.jpg",
  "Reid Hoffman": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2022_Reid_Hoffman_%28cropped%29.jpg/330px-2022_Reid_Hoffman_%28cropped%29.jpg",
  "Richard Feynman": "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Richard_Feynman_Nobel.jpg/330px-Richard_Feynman_Nobel.jpg",
  "Roald Dahl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Roald_Dahl.jpg/200px-Roald_Dahl.jpg",
  "Robert Sapolsky": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Robert_Sapolsky_in_2023_A_16.jpg/330px-Robert_Sapolsky_in_2023_A_16.jpg",
  "Ronald Reagan": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/200px-Official_Portrait_of_President_Reagan_1981.jpg",
  "Ryan Holiday": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/RyanHoliday_%28cropped%29.jpg/330px-RyanHoliday_%28cropped%29.jpg",
  "Sam Harris": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Sam_Harris_2016_%28cropped%29.jpg/200px-Sam_Harris_2016_%28cropped%29.jpg",
  "Seth Godin": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Seth_Godin_in_2009.jpg/200px-Seth_Godin_in_2009.jpg",
  "Shane Parrish": "https://upload.wikimedia.org/wikipedia/en/0/0d/Shane_Parrish.jpg",
  "Shel Silverstein": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Portrait_of_Shel_Silverstein_in_c._1964_by_Jerry_Yulsman.jpg/200px-Portrait_of_Shel_Silverstein_in_c._1964_by_Jerry_Yulsman.jpg",
  "Siddhartha Mukherjee": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Siddhartha_Mukherjee.jpg/330px-Siddhartha_Mukherjee.jpg",
  "Simone de Beauvoir": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Simone_De_Beauvoir_%28cropped%29.jpg/200px-Simone_De_Beauvoir_%28cropped%29.jpg",
  "Stephen Jay Gould": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/SJ_Gould_1985_Flamingos_Smile_Jacket_Photo_by_Eric_Taylor.png/330px-SJ_Gould_1985_Flamingos_Smile_Jacket_Photo_by_Eric_Taylor.png",
  "Stephen King": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Stephen_King_at_the_2024_Toronto_International_Film_Festival_2_%28cropped%29.jpg/200px-Stephen_King_at_the_2024_Toronto_International_Film_Festival_2_%28cropped%29.jpg",
  "Steven Pinker": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Steven_Pinker_in_2023.jpg/330px-Steven_Pinker_in_2023.jpg",
  "Ta-Nehisi Coates": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Ta-Nehisi_Coates_at_the_2025_Edinburgh_International_Book_Festival-21_%28cropped%29.jpg/200px-Ta-Nehisi_Coates_at_the_2025_Edinburgh_International_Book_Festival-21_%28cropped%29.jpg",
  "Taylor Swift": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png/330px-Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png",
  "Theodore Roosevelt": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Theodore_Roosevelt_by_the_Pach_Bros_%284x5_cropped%29.jpg/200px-Theodore_Roosevelt_by_the_Pach_Bros_%284x5_cropped%29.jpg",
  "Tim Ferriss": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Tim_Ferriss.jpg/200px-Tim_Ferriss.jpg",
  "Tim Urban": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Tim_Urban.jpg/200px-Tim_Urban.jpg",
  "Tina Fey": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/TinaFey-byPhilipRomano.jpg/200px-TinaFey-byPhilipRomano.jpg",
  "Tom Wolfe": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/TomWolfe02_%28cropped%29.jpg/200px-TomWolfe02_%28cropped%29.jpg",
  "Toni Morrison": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Toni_Morrison.jpg/200px-Toni_Morrison.jpg",
  "Trevor Noah": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Trevor_Noah_%2853554114243%29_%28portrait_crop%29.jpg/200px-Trevor_Noah_%2853554114243%29_%28portrait_crop%29.jpg",
  "Virginia Woolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg/330px-George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg",
  "Volodymyr Zelenskyy": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Volodymyr_Zelensky_2022_official_portrait_%28cropped%29.jpg/330px-Volodymyr_Zelensky_2022_official_portrait_%28cropped%29.jpg",
  "Walt Whitman": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Walt_Whitman_-_George_Collins_Cox.jpg/330px-Walt_Whitman_-_George_Collins_Cox.jpg",
  "Warren Buffett": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg/200px-Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg",
  "Winston Churchill": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg/200px-Sir_Winston_Churchill_-_19086236948_%28restored%29.jpg",
  "Yuval Noah Harari": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/MKr364751_Yuval_Noah_Harari_%28Frankfurter_Buchmesse_2024%29.jpg/200px-MKr364751_Yuval_Noah_Harari_%28Frankfurter_Buchmesse_2024%29.jpg",
  "Zadie Smith": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Zadie_Smith_NBCC_2011_Shankbone.jpg/200px-Zadie_Smith_NBCC_2011_Shankbone.jpg",
};
